# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61i_orchestrator.proto\x12\x0f\x61i_orchestrator\"\xbb\x01\n\x0fRunCheckRequest\x12\x10\n\x08\x63heck_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x19\n\x11user_profile_json\x18\x03 \x01(\t\x12\x18\n\x10\x63\x61\x64\x61stral_number\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\x12\x0b\n\x03lat\x18\x06 \x01(\x01\x12\x0b\n\x03lng\x18\x07 \x01(\x01\x12\x0f\n\x07purpose\x18\x08 \x01(\t\x12\x14\n\x0c\x64ocument_ids\x18\t \x03(\t\"w\n\x10RunSearchRequest\x12\x11\n\tsearch_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x19\n\x11user_profile_json\x18\x03 \x01(\t\x12\r\n\x05query\x18\x04 \x01(\t\x12\x15\n\rcriteria_json\x18\x05 \x01(\t\"-\n\x0bRunResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\"\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"o\n\x11JobStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rcurrent_agent\x18\x03 \x01(\t\x12\x14\n\x0cprogress_pct\x18\x04 \x01(\x05\x12\r\n\x05\x65rror\x18\x05 \x01(\t2\x81\x02\n\x0e\x41IOrchestrator\x12J\n\x08RunCheck\x12 .ai_orchestrator.RunCheckRequest\x1a\x1c.ai_orchestrator.RunResponse\x12L\n\tRunSearch\x12!.ai_orchestrator.RunSearchRequest\x1a\x1c.ai_orchestrator.RunResponse\x12U\n\x0cGetJobStatus\x12!.ai_orchestrator.JobStatusRequest\x1a\".ai_orchestrator.JobStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNCHECKREQUEST']._serialized_start=43
  _globals['_RUNCHECKREQUEST']._serialized_end=230
  _globals['_RUNSEARCHREQUEST']._serialized_start=232
  _globals['_RUNSEARCHREQUEST']._serialized_end=351
  _globals['_RUNRESPONSE']._serialized_start=353
  _globals['_RUNRESPONSE']._serialized_end=398
  _globals['_JOBSTATUSREQUEST']._serialized_start=400
  _globals['_JOBSTATUSREQUEST']._serialized_end=434
  _globals['_JOBSTATUSRESPONSE']._serialized_start=436
  _globals['_JOBSTATUSRESPONSE']._serialized_end=547
  _globals['_AIORCHESTRATOR']._serialized_start=550
  _globals['_AIORCHESTRATOR']._serialized_end=807
# @@protoc_insertion_point(module_scope)
