# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import check_pb2 as check__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in check_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CheckServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCheck = channel.unary_unary(
                '/check.CheckService/CreateCheck',
                request_serializer=check__pb2.CreateCheckRequest.SerializeToString,
                response_deserializer=check__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.GetCheck = channel.unary_unary(
                '/check.CheckService/GetCheck',
                request_serializer=check__pb2.CheckIdRequest.SerializeToString,
                response_deserializer=check__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.ListChecks = channel.unary_unary(
                '/check.CheckService/ListChecks',
                request_serializer=check__pb2.ListChecksRequest.SerializeToString,
                response_deserializer=check__pb2.ListChecksResponse.FromString,
                _registered_method=True)
        self.GetCheckStatus = channel.unary_unary(
                '/check.CheckService/GetCheckStatus',
                request_serializer=check__pb2.CheckIdRequest.SerializeToString,
                response_deserializer=check__pb2.CheckStatusResponse.FromString,
                _registered_method=True)
        self.GetCheckReport = channel.unary_unary(
                '/check.CheckService/GetCheckReport',
                request_serializer=check__pb2.CheckIdRequest.SerializeToString,
                response_deserializer=check__pb2.CheckReportResponse.FromString,
                _registered_method=True)
        self.UpdateCheckProgress = channel.unary_unary(
                '/check.CheckService/UpdateCheckProgress',
                request_serializer=check__pb2.UpdateProgressRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SaveCheckResult = channel.unary_unary(
                '/check.CheckService/SaveCheckResult',
                request_serializer=check__pb2.SaveResultRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CheckServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChecks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCheckProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCheckResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheck,
                    request_deserializer=check__pb2.CreateCheckRequest.FromString,
                    response_serializer=check__pb2.CheckResponse.SerializeToString,
            ),
            'GetCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheck,
                    request_deserializer=check__pb2.CheckIdRequest.FromString,
                    response_serializer=check__pb2.CheckResponse.SerializeToString,
            ),
            'ListChecks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChecks,
                    request_deserializer=check__pb2.ListChecksRequest.FromString,
                    response_serializer=check__pb2.ListChecksResponse.SerializeToString,
            ),
            'GetCheckStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckStatus,
                    request_deserializer=check__pb2.CheckIdRequest.FromString,
                    response_serializer=check__pb2.CheckStatusResponse.SerializeToString,
            ),
            'GetCheckReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckReport,
                    request_deserializer=check__pb2.CheckIdRequest.FromString,
                    response_serializer=check__pb2.CheckReportResponse.SerializeToString,
            ),
            'UpdateCheckProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCheckProgress,
                    request_deserializer=check__pb2.UpdateProgressRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveCheckResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCheckResult,
                    request_deserializer=check__pb2.SaveResultRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'check.CheckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('check.CheckService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CheckService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/check.CheckService/CreateCheck',
            check__pb2.CreateCheckRequest.SerializeToString,
            check__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/check.CheckService/GetCheck',
            check__pb2.CheckIdRequest.SerializeToString,
            check__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChecks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/check.CheckService/ListChecks',
            check__pb2.ListChecksRequest.SerializeToString,
            check__pb2.ListChecksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/check.CheckService/GetCheckStatus',
            check__pb2.CheckIdRequest.SerializeToString,
            check__pb2.CheckStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/check.CheckService/GetCheckReport',
            check__pb2.CheckIdRequest.SerializeToString,
            check__pb2.CheckReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCheckProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/check.CheckService/UpdateCheckProgress',
            check__pb2.UpdateProgressRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCheckResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/check.CheckService/SaveCheckResult',
            check__pb2.SaveResultRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
