# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import data_collector_pb2 as data__collector__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in data_collector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataCollectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPlotByCadastral = channel.unary_unary(
                '/data_collector.DataCollectorService/GetPlotByCadastral',
                request_serializer=data__collector__pb2.CadastralRequest.SerializeToString,
                response_deserializer=data__collector__pb2.PlotDataResponse.FromString,
                _registered_method=True)
        self.GetPlotByAddress = channel.unary_unary(
                '/data_collector.DataCollectorService/GetPlotByAddress',
                request_serializer=data__collector__pb2.AddressRequest.SerializeToString,
                response_deserializer=data__collector__pb2.PlotDataResponse.FromString,
                _registered_method=True)
        self.GetEGRN = channel.unary_unary(
                '/data_collector.DataCollectorService/GetEGRN',
                request_serializer=data__collector__pb2.EGRNRequest.SerializeToString,
                response_deserializer=data__collector__pb2.EGRNResponse.FromString,
                _registered_method=True)
        self.SearchPlots = channel.unary_unary(
                '/data_collector.DataCollectorService/SearchPlots',
                request_serializer=data__collector__pb2.SearchPlotsRequest.SerializeToString,
                response_deserializer=data__collector__pb2.SearchPlotsResponse.FromString,
                _registered_method=True)
        self.CollectPlotSpatialLayers = channel.unary_unary(
                '/data_collector.DataCollectorService/CollectPlotSpatialLayers',
                request_serializer=data__collector__pb2.SpatialLayersRequest.SerializeToString,
                response_deserializer=data__collector__pb2.SpatialLayersResponse.FromString,
                _registered_method=True)
        self.CollectPlotDataset = channel.unary_unary(
                '/data_collector.DataCollectorService/CollectPlotDataset',
                request_serializer=data__collector__pb2.CadastralRequest.SerializeToString,
                response_deserializer=data__collector__pb2.PlotDatasetResponse.FromString,
                _registered_method=True)


class DataCollectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPlotByCadastral(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlotByAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEGRN(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectPlotSpatialLayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectPlotDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataCollectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPlotByCadastral': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlotByCadastral,
                    request_deserializer=data__collector__pb2.CadastralRequest.FromString,
                    response_serializer=data__collector__pb2.PlotDataResponse.SerializeToString,
            ),
            'GetPlotByAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlotByAddress,
                    request_deserializer=data__collector__pb2.AddressRequest.FromString,
                    response_serializer=data__collector__pb2.PlotDataResponse.SerializeToString,
            ),
            'GetEGRN': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEGRN,
                    request_deserializer=data__collector__pb2.EGRNRequest.FromString,
                    response_serializer=data__collector__pb2.EGRNResponse.SerializeToString,
            ),
            'SearchPlots': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPlots,
                    request_deserializer=data__collector__pb2.SearchPlotsRequest.FromString,
                    response_serializer=data__collector__pb2.SearchPlotsResponse.SerializeToString,
            ),
            'CollectPlotSpatialLayers': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectPlotSpatialLayers,
                    request_deserializer=data__collector__pb2.SpatialLayersRequest.FromString,
                    response_serializer=data__collector__pb2.SpatialLayersResponse.SerializeToString,
            ),
            'CollectPlotDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectPlotDataset,
                    request_deserializer=data__collector__pb2.CadastralRequest.FromString,
                    response_serializer=data__collector__pb2.PlotDatasetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data_collector.DataCollectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('data_collector.DataCollectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataCollectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPlotByCadastral(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data_collector.DataCollectorService/GetPlotByCadastral',
            data__collector__pb2.CadastralRequest.SerializeToString,
            data__collector__pb2.PlotDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlotByAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data_collector.DataCollectorService/GetPlotByAddress',
            data__collector__pb2.AddressRequest.SerializeToString,
            data__collector__pb2.PlotDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEGRN(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data_collector.DataCollectorService/GetEGRN',
            data__collector__pb2.EGRNRequest.SerializeToString,
            data__collector__pb2.EGRNResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data_collector.DataCollectorService/SearchPlots',
            data__collector__pb2.SearchPlotsRequest.SerializeToString,
            data__collector__pb2.SearchPlotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectPlotSpatialLayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data_collector.DataCollectorService/CollectPlotSpatialLayers',
            data__collector__pb2.SpatialLayersRequest.SerializeToString,
            data__collector__pb2.SpatialLayersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectPlotDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data_collector.DataCollectorService/CollectPlotDataset',
            data__collector__pb2.CadastralRequest.SerializeToString,
            data__collector__pb2.PlotDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
