# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import geo_pb2 as geo__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in geo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzePlotLocation = channel.unary_unary(
                '/geo.GeoService/AnalyzePlotLocation',
                request_serializer=geo__pb2.LocationRequest.SerializeToString,
                response_deserializer=geo__pb2.LocationAnalysis.FromString,
                _registered_method=True)
        self.SearchPlotsByArea = channel.unary_unary(
                '/geo.GeoService/SearchPlotsByArea',
                request_serializer=geo__pb2.AreaSearchRequest.SerializeToString,
                response_deserializer=geo__pb2.AreaSearchResponse.FromString,
                _registered_method=True)
        self.GetDistances = channel.unary_unary(
                '/geo.GeoService/GetDistances',
                request_serializer=geo__pb2.DistanceRequest.SerializeToString,
                response_deserializer=geo__pb2.DistanceResponse.FromString,
                _registered_method=True)
        self.CheckProtectedZones = channel.unary_unary(
                '/geo.GeoService/CheckProtectedZones',
                request_serializer=geo__pb2.ZoneRequest.SerializeToString,
                response_deserializer=geo__pb2.ZoneResponse.FromString,
                _registered_method=True)
        self.AnalyzeLandUseRestrictions = channel.unary_unary(
                '/geo.GeoService/AnalyzeLandUseRestrictions',
                request_serializer=geo__pb2.LandUseRestrictionRequest.SerializeToString,
                response_deserializer=geo__pb2.LandUseRestrictionResponse.FromString,
                _registered_method=True)


class GeoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzePlotLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPlotsByArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDistances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckProtectedZones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeLandUseRestrictions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzePlotLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzePlotLocation,
                    request_deserializer=geo__pb2.LocationRequest.FromString,
                    response_serializer=geo__pb2.LocationAnalysis.SerializeToString,
            ),
            'SearchPlotsByArea': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPlotsByArea,
                    request_deserializer=geo__pb2.AreaSearchRequest.FromString,
                    response_serializer=geo__pb2.AreaSearchResponse.SerializeToString,
            ),
            'GetDistances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDistances,
                    request_deserializer=geo__pb2.DistanceRequest.FromString,
                    response_serializer=geo__pb2.DistanceResponse.SerializeToString,
            ),
            'CheckProtectedZones': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckProtectedZones,
                    request_deserializer=geo__pb2.ZoneRequest.FromString,
                    response_serializer=geo__pb2.ZoneResponse.SerializeToString,
            ),
            'AnalyzeLandUseRestrictions': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeLandUseRestrictions,
                    request_deserializer=geo__pb2.LandUseRestrictionRequest.FromString,
                    response_serializer=geo__pb2.LandUseRestrictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geo.GeoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('geo.GeoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzePlotLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoService/AnalyzePlotLocation',
            geo__pb2.LocationRequest.SerializeToString,
            geo__pb2.LocationAnalysis.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPlotsByArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoService/SearchPlotsByArea',
            geo__pb2.AreaSearchRequest.SerializeToString,
            geo__pb2.AreaSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDistances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoService/GetDistances',
            geo__pb2.DistanceRequest.SerializeToString,
            geo__pb2.DistanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckProtectedZones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoService/CheckProtectedZones',
            geo__pb2.ZoneRequest.SerializeToString,
            geo__pb2.ZoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeLandUseRestrictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoService/AnalyzeLandUseRestrictions',
            geo__pb2.LandUseRestrictionRequest.SerializeToString,
            geo__pb2.LandUseRestrictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
