# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import market_pb2 as market__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in market_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMarketAnalysis = channel.unary_unary(
                '/market.MarketService/GetMarketAnalysis',
                request_serializer=market__pb2.MarketRequest.SerializeToString,
                response_deserializer=market__pb2.MarketAnalysis.FromString,
                _registered_method=True)
        self.GetComparables = channel.unary_unary(
                '/market.MarketService/GetComparables',
                request_serializer=market__pb2.ComparablesRequest.SerializeToString,
                response_deserializer=market__pb2.ComparablesResponse.FromString,
                _registered_method=True)
        self.GetPriceStats = channel.unary_unary(
                '/market.MarketService/GetPriceStats',
                request_serializer=market__pb2.PriceStatsRequest.SerializeToString,
                response_deserializer=market__pb2.PriceStatsResponse.FromString,
                _registered_method=True)


class MarketServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMarketAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComparables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPriceStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMarketAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketAnalysis,
                    request_deserializer=market__pb2.MarketRequest.FromString,
                    response_serializer=market__pb2.MarketAnalysis.SerializeToString,
            ),
            'GetComparables': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComparables,
                    request_deserializer=market__pb2.ComparablesRequest.FromString,
                    response_serializer=market__pb2.ComparablesResponse.SerializeToString,
            ),
            'GetPriceStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPriceStats,
                    request_deserializer=market__pb2.PriceStatsRequest.FromString,
                    response_serializer=market__pb2.PriceStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'market.MarketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('market.MarketService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMarketAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/market.MarketService/GetMarketAnalysis',
            market__pb2.MarketRequest.SerializeToString,
            market__pb2.MarketAnalysis.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComparables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/market.MarketService/GetComparables',
            market__pb2.ComparablesRequest.SerializeToString,
            market__pb2.ComparablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPriceStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/market.MarketService/GetPriceStats',
            market__pb2.PriceStatsRequest.SerializeToString,
            market__pb2.PriceStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
