# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import search_pb2 as search__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSearch = channel.unary_unary(
                '/search.SearchService/CreateSearch',
                request_serializer=search__pb2.CreateSearchRequest.SerializeToString,
                response_deserializer=search__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetSearch = channel.unary_unary(
                '/search.SearchService/GetSearch',
                request_serializer=search__pb2.SearchIdRequest.SerializeToString,
                response_deserializer=search__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.ListSearches = channel.unary_unary(
                '/search.SearchService/ListSearches',
                request_serializer=search__pb2.ListSearchesRequest.SerializeToString,
                response_deserializer=search__pb2.ListSearchesResponse.FromString,
                _registered_method=True)
        self.GetSearchStatus = channel.unary_unary(
                '/search.SearchService/GetSearchStatus',
                request_serializer=search__pb2.SearchIdRequest.SerializeToString,
                response_deserializer=search__pb2.SearchStatusResponse.FromString,
                _registered_method=True)
        self.GetSearchCriteria = channel.unary_unary(
                '/search.SearchService/GetSearchCriteria',
                request_serializer=search__pb2.SearchIdRequest.SerializeToString,
                response_deserializer=search__pb2.SearchCriteriaResponse.FromString,
                _registered_method=True)
        self.ConfirmCriteria = channel.unary_unary(
                '/search.SearchService/ConfirmCriteria',
                request_serializer=search__pb2.ConfirmCriteriaRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetSearchResults = channel.unary_unary(
                '/search.SearchService/GetSearchResults',
                request_serializer=search__pb2.SearchIdRequest.SerializeToString,
                response_deserializer=search__pb2.SearchResultsResponse.FromString,
                _registered_method=True)
        self.GetRecommendation = channel.unary_unary(
                '/search.SearchService/GetRecommendation',
                request_serializer=search__pb2.SearchIdRequest.SerializeToString,
                response_deserializer=search__pb2.RecommendationResponse.FromString,
                _registered_method=True)
        self.SaveCriteria = channel.unary_unary(
                '/search.SearchService/SaveCriteria',
                request_serializer=search__pb2.SaveCriteriaRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SaveCandidate = channel.unary_unary(
                '/search.SearchService/SaveCandidate',
                request_serializer=search__pb2.SaveCandidateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateSearchProgress = channel.unary_unary(
                '/search.SearchService/UpdateSearchProgress',
                request_serializer=search__pb2.UpdateProgressRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSearches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSearchStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSearchCriteria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmCriteria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSearchResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCriteria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCandidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSearchProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSearch,
                    request_deserializer=search__pb2.CreateSearchRequest.FromString,
                    response_serializer=search__pb2.SearchResponse.SerializeToString,
            ),
            'GetSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSearch,
                    request_deserializer=search__pb2.SearchIdRequest.FromString,
                    response_serializer=search__pb2.SearchResponse.SerializeToString,
            ),
            'ListSearches': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSearches,
                    request_deserializer=search__pb2.ListSearchesRequest.FromString,
                    response_serializer=search__pb2.ListSearchesResponse.SerializeToString,
            ),
            'GetSearchStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSearchStatus,
                    request_deserializer=search__pb2.SearchIdRequest.FromString,
                    response_serializer=search__pb2.SearchStatusResponse.SerializeToString,
            ),
            'GetSearchCriteria': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSearchCriteria,
                    request_deserializer=search__pb2.SearchIdRequest.FromString,
                    response_serializer=search__pb2.SearchCriteriaResponse.SerializeToString,
            ),
            'ConfirmCriteria': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmCriteria,
                    request_deserializer=search__pb2.ConfirmCriteriaRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetSearchResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSearchResults,
                    request_deserializer=search__pb2.SearchIdRequest.FromString,
                    response_serializer=search__pb2.SearchResultsResponse.SerializeToString,
            ),
            'GetRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendation,
                    request_deserializer=search__pb2.SearchIdRequest.FromString,
                    response_serializer=search__pb2.RecommendationResponse.SerializeToString,
            ),
            'SaveCriteria': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCriteria,
                    request_deserializer=search__pb2.SaveCriteriaRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCandidate,
                    request_deserializer=search__pb2.SaveCandidateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateSearchProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSearchProgress,
                    request_deserializer=search__pb2.UpdateProgressRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search.SearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('search.SearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/CreateSearch',
            search__pb2.CreateSearchRequest.SerializeToString,
            search__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/GetSearch',
            search__pb2.SearchIdRequest.SerializeToString,
            search__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSearches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/ListSearches',
            search__pb2.ListSearchesRequest.SerializeToString,
            search__pb2.ListSearchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSearchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/GetSearchStatus',
            search__pb2.SearchIdRequest.SerializeToString,
            search__pb2.SearchStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSearchCriteria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/GetSearchCriteria',
            search__pb2.SearchIdRequest.SerializeToString,
            search__pb2.SearchCriteriaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmCriteria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/ConfirmCriteria',
            search__pb2.ConfirmCriteriaRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSearchResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/GetSearchResults',
            search__pb2.SearchIdRequest.SerializeToString,
            search__pb2.SearchResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/GetRecommendation',
            search__pb2.SearchIdRequest.SerializeToString,
            search__pb2.RecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCriteria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/SaveCriteria',
            search__pb2.SaveCriteriaRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/SaveCandidate',
            search__pb2.SaveCandidateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSearchProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/UpdateSearchProgress',
            search__pb2.UpdateProgressRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
