from __future__ import annotations

from app.layers.models import LayerCatalogEntry, ScenarioEffect


AGRICULTURE = "agriculture"
RENT = "rent"
CONSTRUCTION = "construction"


def _effects(
    *,
    agriculture: str = "warning_only",
    rent: str = "warning_only",
    construction: str = "warning_only",
    show_agriculture: bool = True,
    show_rent: bool = True,
    show_construction: bool = True,
) -> dict[str, ScenarioEffect]:
    return {
        AGRICULTURE: ScenarioEffect(agriculture, show_agriculture),
        RENT: ScenarioEffect(rent, show_rent),
        CONSTRUCTION: ScenarioEffect(construction, show_construction),
    }


IGNORED_FOR_AGRI = _effects(
    agriculture="ignore",
    rent="ignore",
    construction="warning_only",
    show_agriculture=False,
    show_rent=False,
    show_construction=True,
)


LAYER_CATALOG: dict[str, LayerCatalogEntry] = {
    "buildings": LayerCatalogEntry(
        key="buildings",
        source_group="capital_construction",
        source_name="Здания",
        payload_kind="real_estate_object",
        normalized_type="building",
        label="Здание на земельном участке",
    ),
    "structures": LayerCatalogEntry(
        key="structures",
        source_group="capital_construction",
        source_name="Сооружения",
        payload_kind="real_estate_object",
        normalized_type="structure",
        label="Сооружение на земельном участке",
    ),
    "unfinished_construction": LayerCatalogEntry(
        key="unfinished_construction",
        source_group="capital_construction",
        source_name="Объекты незавершенного строительства",
        payload_kind="real_estate_object",
        normalized_type="unfinished_construction",
        label="Объект незавершенного строительства",
    ),
    "single_real_estate_complex": LayerCatalogEntry(
        key="single_real_estate_complex",
        source_group="object_complexes",
        source_name="Единые недвижимые комплексы",
        payload_kind="real_estate_object",
        normalized_type="single_real_estate_complex",
        label="Единый недвижимый комплекс",
    ),
    "enterprise_property_complex": LayerCatalogEntry(
        key="enterprise_property_complex",
        source_group="object_complexes",
        source_name="Предприятие как имущественный комплекс",
        payload_kind="real_estate_object",
        normalized_type="enterprise_complex",
        label="Предприятие как имущественный комплекс",
    ),
    "cultural_heritage_zouit": LayerCatalogEntry(
        key="cultural_heritage_zouit",
        source_group="zouit",
        source_name="ЗОУИТ объектов культурного наследия",
        payload_kind="restriction",
        normalized_type="cultural_heritage_protection_zone",
        label="ЗОУИТ объекта культурного наследия",
        severity="hard_limit",
        default_restrictions=("Режим охраны может ограничивать строительство, земляные работы и хозяйственную деятельность.",),
        normative_basis=("ФЗ N 73-ФЗ об объектах культурного наследия",),
        scenario_effects=_effects(construction="exclude_from_usable"),
    ),
    "energy_transport_zouit": LayerCatalogEntry(
        key="energy_transport_zouit",
        source_group="zouit",
        source_name="ЗОУИТ объектов энергетики, связи, транспорта",
        payload_kind="restriction",
        normalized_type="power_transport_communication_zone",
        label="Охранная зона инженерного или транспортного объекта",
        severity="restricted_use",
        default_restrictions=("Режим зависит от вида линейного, энергетического или транспортного объекта.",),
        normative_basis=("Сведения ЕГРН о ЗОУИТ и профильный режим охранной зоны",),
        scenario_effects=_effects(construction="exclude_from_usable"),
    ),
    "natural_area_zouit": LayerCatalogEntry(
        key="natural_area_zouit",
        source_group="zouit",
        source_name="ЗОУИТ природных территорий",
        payload_kind="restriction",
        normalized_type="protected_natural_area",
        label="ЗОУИТ природной территории",
        severity="hard_limit",
        default_restrictions=("Может запрещать или существенно ограничивать сельхозиспользование и строительство.",),
        normative_basis=("Сведения ЕГРН о ЗОУИТ, положение об охраняемой территории",),
        scenario_effects=_effects(agriculture="exclude_from_usable", rent="exclude_from_usable", construction="exclude_from_usable"),
    ),
    "security_zouit": LayerCatalogEntry(
        key="security_zouit",
        source_group="zouit",
        source_name="ЗОУИТ охраняемых объектов и безопасности",
        payload_kind="restriction",
        normalized_type="security_zone",
        label="Охранная зона объекта безопасности",
        severity="hard_limit",
        default_restrictions=("Режим зоны безопасности требует отдельной проверки по объекту.",),
        normative_basis=("Сведения ЕГРН о ЗОУИТ",),
        scenario_effects=_effects(construction="exclude_from_usable"),
    ),
    "other_zouit": LayerCatalogEntry(
        key="other_zouit",
        source_group="zouit",
        source_name="Иные ЗОУИТ",
        payload_kind="restriction",
        normalized_type="other_zouit",
        label="Иная зона с особыми условиями использования",
        severity="restricted_use",
        default_restrictions=("Нужно проверить вид зоны и ее режим по ЕГРН/акту установления.",),
        normative_basis=("Сведения ЕГРН о ЗОУИТ",),
        scenario_effects=_effects(),
    ),
    "territorial_zones": LayerCatalogEntry(
        key="territorial_zones",
        source_group="planning",
        source_name="Территориальные зоны",
        payload_kind="restriction",
        normalized_type="territorial_zone",
        label="Территориальная зона",
        severity="restricted_use",
        default_restrictions=("Проверяется соответствие ВРИ градостроительному регламенту.",),
        normative_basis=("ПЗЗ муниципального образования",),
        scenario_effects=_effects(),
    ),
    "red_lines": LayerCatalogEntry(
        key="red_lines",
        source_group="planning",
        source_name="Красные линии",
        payload_kind="restriction",
        normalized_type="red_line",
        label="Красная линия",
        severity="hard_limit",
        default_restrictions=("Ограничивает размещение объектов капитального строительства.",),
        normative_basis=("Градостроительный кодекс РФ, документация по планировке территории",),
        scenario_effects=_effects(construction="exclude_from_usable"),
    ),
    "oopt": LayerCatalogEntry(
        key="oopt",
        source_group="natural_territories",
        source_name="Особо охраняемые природные территории",
        payload_kind="restriction",
        normalized_type="protected_natural_area",
        label="Особо охраняемая природная территория",
        severity="hard_limit",
        default_restrictions=("Режим ООПТ может запрещать или ограничивать обработку земли.",),
        normative_basis=("ФЗ N 33-ФЗ об особо охраняемых природных территориях",),
        scenario_effects=_effects(agriculture="exclude_from_usable", rent="exclude_from_usable", construction="exclude_from_usable"),
    ),
    "hunting_grounds": LayerCatalogEntry(
        key="hunting_grounds",
        source_group="natural_territories",
        source_name="Охотничьи угодья",
        payload_kind="restriction",
        normalized_type="hunting_ground",
        label="Охотничье угодье",
        severity="info",
        default_restrictions=("Обычно не исключает площадь, но важно как соседний режим использования.",),
        normative_basis=("Сведения об охотничьих угодьях",),
        scenario_effects=_effects(),
    ),
    "forestry": LayerCatalogEntry(
        key="forestry",
        source_group="natural_territories",
        source_name="Лесничества",
        payload_kind="restriction",
        normalized_type="forest",
        label="Лесничество / лесной фонд",
        severity="restricted_use",
        default_restrictions=("Нужно проверить пересечение с лесным фондом и допустимость сельхозиспользования.",),
        normative_basis=("Лесной кодекс РФ / сведения лесного реестра",),
        scenario_effects=_effects(agriculture="exclude_from_usable", rent="exclude_from_usable", construction="exclude_from_usable"),
    ),
    "forest_park_boundary": LayerCatalogEntry(
        key="forest_park_boundary",
        source_group="natural_territories",
        source_name="Граница лесопарка",
        payload_kind="restriction",
        normalized_type="forest_park_boundary",
        label="Граница лесопарка",
        severity="restricted_use",
        default_restrictions=("Требует проверки режима лесопарковой территории.",),
        normative_basis=("Лесной кодекс РФ / сведения лесного реестра",),
        scenario_effects=_effects(construction="exclude_from_usable"),
    ),
    "water_boundary_polygon": LayerCatalogEntry(
        key="water_boundary_polygon",
        source_group="natural_territories",
        source_name="Береговые линии, полигональный слой",
        payload_kind="restriction",
        normalized_type="coastal_protective_strip",
        label="Береговая линия / прибрежная защитная полоса",
        severity="hard_limit",
        default_restrictions=("В прибрежной защитной полосе запрещена распашка земель.",),
        normative_basis=("Водный кодекс РФ, статья 65",),
        scenario_effects=_effects(agriculture="exclude_from_usable", rent="exclude_from_usable", construction="exclude_from_usable"),
    ),
    "water_boundary_line": LayerCatalogEntry(
        key="water_boundary_line",
        source_group="natural_territories",
        source_name="Береговые линии, линейный слой",
        payload_kind="restriction",
        normalized_type="shoreline",
        label="Береговая линия",
        severity="restricted_use",
        default_restrictions=("Линейный слой нужен для построения/уточнения водоохранных и прибрежных зон.",),
        normative_basis=("Водный кодекс РФ, статья 65",),
        scenario_effects=_effects(),
    ),
    "special_economic_zone": LayerCatalogEntry(
        key="special_economic_zone",
        source_group="socio_economic",
        source_name="Особые экономические зоны",
        payload_kind="info",
        normalized_type="special_economic_zone",
        label="Особая экономическая зона",
        scenario_effects=_effects(),
    ),
    "advanced_development_territory": LayerCatalogEntry(
        key="advanced_development_territory",
        source_group="socio_economic",
        source_name="Территория опережающего развития",
        payload_kind="info",
        normalized_type="advanced_development_territory",
        label="Территория опережающего развития",
        scenario_effects=_effects(),
    ),
    "gambling_zone": LayerCatalogEntry(
        key="gambling_zone",
        source_group="socio_economic",
        source_name="Игорные зоны",
        payload_kind="restriction",
        normalized_type="gambling_zone",
        label="Игорная зона",
        severity="info",
        default_restrictions=("Для сельхозсценария не влияет на полезную площадь.",),
        normative_basis=("Сведения о зонах социально-экономического развития",),
        scenario_effects=IGNORED_FOR_AGRI,
    ),
    "heritage_registry_territory": LayerCatalogEntry(
        key="heritage_registry_territory",
        source_group="cultural_heritage",
        source_name="Территории объектов культурного наследия из госреестра",
        payload_kind="restriction",
        normalized_type="heritage_site_territory",
        label="Территория объекта культурного наследия",
        severity="hard_limit",
        default_restrictions=("Режим территории ОКН требует отдельной правовой проверки.",),
        normative_basis=("ФЗ N 73-ФЗ об объектах культурного наследия",),
        scenario_effects=_effects(agriculture="exclude_from_usable", rent="exclude_from_usable", construction="exclude_from_usable"),
    ),
    "heritage_object_territory": LayerCatalogEntry(
        key="heritage_object_territory",
        source_group="cultural_heritage",
        source_name="Территории объектов культурного наследия",
        payload_kind="restriction",
        normalized_type="heritage_site_territory",
        label="Территория объекта культурного наследия",
        severity="hard_limit",
        default_restrictions=("Режим территории ОКН требует отдельной правовой проверки.",),
        normative_basis=("ФЗ N 73-ФЗ об объектах культурного наследия",),
        scenario_effects=_effects(agriculture="exclude_from_usable", rent="exclude_from_usable", construction="exclude_from_usable"),
    ),
    "complex_cadastral_works": LayerCatalogEntry(
        key="complex_cadastral_works",
        source_group="other_territories",
        source_name="Территории выполнения комплексных кадастровых работ",
        payload_kind="info",
        normalized_type="complex_cadastral_works",
        label="Территория комплексных кадастровых работ",
    ),
    "environmental_damage_cleanup": LayerCatalogEntry(
        key="environmental_damage_cleanup",
        source_group="other_territories",
        source_name="Территория мероприятий по ликвидации накопленного вреда",
        payload_kind="restriction",
        normalized_type="environmental_damage_cleanup",
        label="Территория ликвидации накопленного вреда окружающей среде",
        severity="hard_limit",
        default_restrictions=("Требуется экологическая и правовая проверка ограничений использования.",),
        normative_basis=("Акт о территории ликвидации накопленного вреда окружающей среде",),
        scenario_effects=_effects(agriculture="exclude_from_usable", rent="exclude_from_usable", construction="exclude_from_usable"),
    ),
    "water_erosion": LayerCatalogEntry(
        key="water_erosion",
        source_group="negative_processes",
        source_name="Водная эрозия",
        payload_kind="restriction",
        normalized_type="erosion",
        label="Водная эрозия",
        severity="restricted_use",
        default_restrictions=("Не исключает площадь автоматически, но снижает агропригодность и требует противоэрозионных мероприятий.",),
        normative_basis=("Материалы мониторинга земель / землеустройства",),
        scenario_effects=_effects(),
    ),
    "linear_erosion": LayerCatalogEntry(
        key="linear_erosion",
        source_group="negative_processes",
        source_name="Линейная эрозия",
        payload_kind="restriction",
        normalized_type="erosion",
        label="Линейная эрозия",
        severity="restricted_use",
        default_restrictions=("Не исключает площадь автоматически, но требует учета оврагов, промоин и мер защиты почв.",),
        normative_basis=("Материалы мониторинга земель / землеустройства",),
        scenario_effects=_effects(),
    ),
    "wind_erosion": LayerCatalogEntry(
        key="wind_erosion",
        source_group="negative_processes",
        source_name="Ветровая эрозия",
        payload_kind="restriction",
        normalized_type="erosion",
        label="Ветровая эрозия",
        severity="restricted_use",
        default_restrictions=("Не исключает площадь автоматически, но требует противодефляционных мероприятий.",),
        normative_basis=("Материалы мониторинга земель / землеустройства",),
        scenario_effects=_effects(),
    ),
    "desertification": LayerCatalogEntry(
        key="desertification",
        source_group="negative_processes",
        source_name="Опустынивание",
        payload_kind="restriction",
        normalized_type="desertification",
        label="Опустынивание",
        severity="restricted_use",
        default_restrictions=("Снижает агропригодность; итоговый режим зависит от материалов мониторинга.",),
        normative_basis=("Материалы мониторинга земель",),
        scenario_effects=_effects(),
    ),
    "overmoistening": LayerCatalogEntry(
        key="overmoistening",
        source_group="negative_processes",
        source_name="Переувлажнение",
        payload_kind="restriction",
        normalized_type="waterlogging",
        label="Переувлажнение",
        severity="restricted_use",
        default_restrictions=("Может ограничивать обработку и требовать мелиорации.",),
        normative_basis=("Материалы мониторинга земель",),
        scenario_effects=_effects(),
    ),
    "underflooding": LayerCatalogEntry(
        key="underflooding",
        source_group="negative_processes",
        source_name="Подтопление",
        payload_kind="restriction",
        normalized_type="underflooding_zone",
        label="Подтопление",
        severity="restricted_use",
        default_restrictions=("Для строительства может быть стоп-фактором; для сельхозиспользования требует инженерной оценки.",),
        normative_basis=("Сведения о зонах подтопления",),
        scenario_effects=_effects(construction="exclude_from_usable"),
    ),
    "bogging": LayerCatalogEntry(
        key="bogging",
        source_group="negative_processes",
        source_name="Заболачивание",
        payload_kind="restriction",
        normalized_type="waterlogging",
        label="Заболачивание",
        severity="restricted_use",
        default_restrictions=("Может ограничивать обработку и требовать мелиорации.",),
        normative_basis=("Материалы мониторинга земель",),
        scenario_effects=_effects(),
    ),
    "flooding": LayerCatalogEntry(
        key="flooding",
        source_group="negative_processes",
        source_name="Затопление",
        payload_kind="restriction",
        normalized_type="flooding_zone",
        label="Затопление",
        severity="hard_limit",
        default_restrictions=("Риск затопления; для строительства может быть стоп-фактором.",),
        normative_basis=("Сведения о зонах затопления",),
        scenario_effects=_effects(construction="exclude_from_usable"),
    ),
    "littering": LayerCatalogEntry(
        key="littering",
        source_group="negative_processes",
        source_name="Захламление",
        payload_kind="restriction",
        normalized_type="littering",
        label="Захламление",
        severity="restricted_use",
        default_restrictions=("Требует проверки фактического состояния и затрат на рекультивацию/очистку.",),
        normative_basis=("Материалы мониторинга земель",),
        scenario_effects=_effects(),
    ),
    "landslide": LayerCatalogEntry(
        key="landslide",
        source_group="negative_processes",
        source_name="Обвально-осыпные и оползневые процессы",
        payload_kind="restriction",
        normalized_type="landslide",
        label="Оползневые и обвально-осыпные процессы",
        severity="hard_limit",
        default_restrictions=("Требует инженерно-геологической проверки; для строительства может исключать площадь.",),
        normative_basis=("Материалы мониторинга земель / инженерно-геологические сведения",),
        scenario_effects=_effects(construction="exclude_from_usable"),
    ),
    "abrasion": LayerCatalogEntry(
        key="abrasion",
        source_group="negative_processes",
        source_name="Абразия",
        payload_kind="restriction",
        normalized_type="abrasion",
        label="Абразия",
        severity="restricted_use",
        default_restrictions=("Береговой негативный процесс, требует проверки устойчивости и режима использования.",),
        normative_basis=("Материалы мониторинга земель",),
        scenario_effects=_effects(),
    ),
    "disturbed_land": LayerCatalogEntry(
        key="disturbed_land",
        source_group="negative_processes",
        source_name="Нарушенные земли",
        payload_kind="restriction",
        normalized_type="disturbed_land",
        label="Нарушенные земли",
        severity="restricted_use",
        default_restrictions=("Требует оценки рекультивации и фактической пригодности к использованию.",),
        normative_basis=("Материалы мониторинга земель",),
        scenario_effects=_effects(),
    ),
    "burned_area": LayerCatalogEntry(
        key="burned_area",
        source_group="negative_processes",
        source_name="Гари",
        payload_kind="restriction",
        normalized_type="burned_area",
        label="Гари",
        severity="restricted_use",
        default_restrictions=("Требует проверки восстановления растительности и фактического состояния.",),
        normative_basis=("Материалы мониторинга земель",),
        scenario_effects=_effects(),
    ),
    "salinization": LayerCatalogEntry(
        key="salinization",
        source_group="negative_processes",
        source_name="Засоление",
        payload_kind="restriction",
        normalized_type="salinization",
        label="Засоление",
        severity="restricted_use",
        default_restrictions=("Снижает агропригодность и может требовать мелиоративных мероприятий.",),
        normative_basis=("Материалы мониторинга земель / агрохимическое обследование",),
        scenario_effects=_effects(),
    ),
    "negative_process_absent": LayerCatalogEntry(
        key="negative_process_absent",
        source_group="negative_processes",
        source_name="Негативный процесс отсутствует",
        payload_kind="info",
        normalized_type="negative_process_absent",
        label="Негативный процесс отсутствует",
    ),
    "cadastral_value": LayerCatalogEntry(
        key="cadastral_value",
        source_group="thematic_maps",
        source_name="Кадастровая стоимость объекта",
        payload_kind="valuation",
        normalized_type="cadastral_value",
        label="Кадастровая стоимость объекта",
    ),
    "cadastral_value_index": LayerCatalogEntry(
        key="cadastral_value_index",
        source_group="thematic_maps",
        source_name="Удельный показатель кадастровой стоимости",
        payload_kind="valuation",
        normalized_type="cadastral_value_index",
        label="Удельный показатель кадастровой стоимости",
    ),
}


DISTURBED_LAND_LAYER_KEYS = {
    "disturbed_land_surface_construction",
    "disturbed_land_hydrotechnical_construction",
    "disturbed_land_subsoil_use",
    "disturbed_land_industrial_forest_use",
    "disturbed_land_agricultural_development",
    "disturbed_land_geological_works",
    "disturbed_land_waste_storage",
}


def get_catalog_entry(layer_key: str) -> LayerCatalogEntry | None:
    if layer_key in DISTURBED_LAND_LAYER_KEYS:
        return LAYER_CATALOG["disturbed_land"]
    return LAYER_CATALOG.get(layer_key)

